// ___PROJECTNAME___ by ___ORGANIZATIONNAME___
// Copyright (c) ___YEAR___ All rights reserved.

#ifndef ___PROJECTNAMEASIDENTIFIER_______FILEBASENAMEASIDENTIFIER_______FILEEXTENSION___
#define ___PROJECTNAMEASIDENTIFIER_______FILEBASENAMEASIDENTIFIER_______FILEEXTENSION___



#endif
