// ___PROJECTNAME___ by ___ORGANIZATIONNAME___
// Copyright (c) ___YEAR___ All rights reserved.

#import "___FILEBASENAME___.h"
___COREDATAMANAGEDOBJECTIMPORTEDHEADERS___

@implementation ___FILEBASENAMEASIDENTIFIER___

___COREDATAPROPERTYIMPLEMENTATIONS___
@end
