// ___PROJECTNAME___ by ___ORGANIZATIONNAME___
// Copyright (c) ___YEAR___ All rights reserved.

#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>
___COREDATAMANAGEDOBJECTSUPERCLASSIMPORT___
___COREDATAMANAGEDOBJECTCLASSREFERENCES___
@interface ___FILEBASENAMEASIDENTIFIER___ : ___COREDATAMANAGEDOBJECTSUPERCLASS___

___COREDATAPROPERTYDECLARATIONS___
@end
